### PR TITLE
Improvements for image.save()

### PR DESCRIPTION
**Pull request by Joe7M**
Hi Chris,

I wanted to use image.clip() and image.save() to split a tilemap into tiles but realized, that it was not possible. I did some improvements to the image save function. Now you can do the following:

```
png.save("horse1.png")
png.save(#1)
png.save(byref var)
file = "abc.png" : png.save(file)
```

Especially the last line was not possible. When a variable was passed as an argument, the variable was always transformed to an array and the image values were returned in this array. When now a string-variable with a file name is given as an argument, the file will be save to that file name. 

Additionally when saving to an array, the settings of image.clip will be applied instead of returning the full image.

At the moment I did it only for image.cpp in the ui folder. If you like the changes, I can also rewrite the console part.

Best regards, Joerg

### CODE REVIEW

**Comment by Joe7M** [comment]
In the second commit, I fixed a bug in image.clip(), which crashes SB, when providing negative coordinates. I also added some bound checks for image.save().

**Comment by Joe7M** [comment]
In the third commit I fixed a bug when opening a serial port: When using COMx, SB opened COM(x-1) : COM5 -> COM4.

**Comment by Joe7M** [comment]
Hi Chris,

one more commit. This time I improved the serial port. I wanted to connect to a Raspberry Pi Pico in Linux. I realized, that this is not possible, because the Pico creates a serial port called `/dev/ttyACMn` and SmallBASIC was only able to open `/dev/ttySn`. The same for Arduino. Some other devices creating a serial port `/dev/ttyUSBn`. So I started to improve the serial port in Linux and Windows. Here the changes:

- [Linux] `/dev/ttyUSBn`, `/dev/ttyACMn` and other serial port devices starting with `/dev/tty` can now be opened: `open "/dev/ttyUSB1:9600" as #1"`
- [Windows] COM-port 10 to 99 can be opened
- [Windows] serial connection with Raspberry Pi Pico using the Pico's USB-port is working now
- [Linux and Windows]: Baud rate can be set to values higher than 38400 (up to 4000000)

I tested in Linux Manjaro and Windows 11 using Arduino Uno, Raspberry Pi Pico and Adafruit Feather M0 Express.

Best regards, Joerg

**Review by chrisws — APPROVED** [review]

**Comment by chrisws** [comment]
Looks good. 

Sorry I only recently notices this PR. 

Cheers,
Chris

**Pull request merged**
