### PR TITLE
Update configure.ac

### PR DESCRIPTION
**Pull request by iahung3**
Fix linking issue on MSYS2

### CODE REVIEW

**Comment by iahung3** [comment]
@chrisws

**Comment by chrisws** [comment]
Hi iahung3,

Thanks for your patch. Unfortunately this breaks cross compiling the windows version under linux. 

On my system `pkg-config -libs -static freetype2` gives `Unknown option -libs`

You could try changing it to `pkg-config freetype2 --libs --static` or alternatively this:

```
     if test $build_os = 'linux-gnu'; then
       PACKAGE_LIBS="${PACKAGE_LIBS} `sdl2-config --static-libs` `pkg-config freetype2 --libs`"
     else        
       PACKAGE_LIBS="${PACKAGE_LIBS} `sdl2-config --static-libs` `pkg-config -libs -static freetype2`"
     fi  
```

**Comment by iahung3** [comment]
> You could try changing it to `pkg-config freetype2 --libs --static`

Done. Thank you.

**Review by chrisws — APPROVED** [review]
That seems fine now.

**Pull request merged**
